Added better error handling
ProcursusTeam/ldid pull request #13
Opened 2022-04-04 23:01 UTC by K0stad1n

Started replacing asserts with if statements to check for errors

2022-04-04 23:11 UTC, CRKatri commented
Thanks for getting started on this.

2022-04-04 23:12 UTC, CRKatri requested changes

2022-04-04 23:12 UTC, CRKatri commented on ldid.cpp
> +    }
The spacing on these lines are incorrect

2022-04-04 23:12 UTC, CRKatri commented on ldid.cpp
> +        printf("An Error occured while parsing: \n %s\n You're p12 cert might not be valid", ERR_error_string(ERR_get_error(), NULL));
```suggestion
        printf("An Error occured while parsing: \n %s\n Your p12 cert might not be valid", ERR_error_string(ERR_get_error(), NULL));
```

2022-04-05 03:42 UTC, K0stad1n commented
@CRKatri Should there be a version bump for Ldid once error checking is done?

2022-04-05 04:37 UTC, CRKatri commented on ldid.cpp
> +            printf("An error occured while parsing: \n %s\n", ERR_error_string(ERR_get_error(), NULL));
Please don't re-add those newlines, I had removed them on purpose.

2022-04-05 04:37 UTC, CRKatri commented
> Should there be a version bump for Ldid once error checking is done?

That is the current plan.

2022-04-05 05:22 UTC, demhademha commented
We should ideally use exit(EXIT_FAILURE);

2022-04-05 05:23 UTC, demhademha commented
And EXIT_SUCCESS

2022-04-05 07:57 UTC, K0stad1n commented
> > Should there be a version bump for Ldid once error checking is done?
> 
> 
> 
> That is the current plan.

What should the new version number be do you think?

2022-04-05 11:50 UTC, CRKatri commented
> > > Should there be a version bump for Ldid once error checking is done?
> > 
> > 
> > That is the current plan.
> 
> What should the new version number be do you think?

It will be `2.1.5-procursus3`. The first number is the upstream version number from git.saurik.com/ldid.git. Then we do `-procursus*` to show the Procursus patch version.

2022-04-30 15:28 UTC, absidue requested changes

2022-04-30 15:28 UTC, absidue commented on ldid.cpp
> +                fprintf(stderr, "ldid: Only -S can be used on directores\n");
```suggestion
                fprintf(stderr, "ldid: Only -S can be used on directories\n");
```

2022-04-30 15:36 UTC, absidue approved these changes

2022-05-03 20:12 UTC, 1Conan approved these changes

2022-05-04 04:00 UTC, merged