add linker-signed support
ProcursusTeam/ldid pull request #27
Opened 2022-11-26 10:41 UTC by excitedplus1s

usage:
ldid -S -Cadhoc -Clinker-signed somfile

codesign -dv -r- somefile

CodeDirectory v=20400 size=7071 flags=0x20002(adhoc,**linker-signed**) hashes=216+2 location=embedded

2022-11-26 13:12 UTC, CRKatri commented
Please add this to the manpage.

2022-11-26 20:49 UTC, CRKatri commented
Thank you!
If you're up to the challenge, would you like to add support for using multiple flags with one `-C`, like `-Chard,kill`? It should be fairly simple to implement with [`getsubopt(3p)`](http://man.ckatri.com/POSIX-2017/man3p/getsubopt.3p) or [`strtok(3p)`](http://man.ckatri.com/POSIX-2017/strtok.3).

2022-11-27 03:54 UTC, excitedplus1s commented
> Thank you!
> If you're up to the challenge, would you like to add support for using multiple flags with one `-C`, like `-Chard,kill`? It should be fairly simple to implement with [`getsubopt(3p)`](http://man.ckatri.com/POSIX-2017/man3p/getsubopt.3p) or [`strtok(3p)`](http://man.ckatri.com/POSIX-2017/strtok.3).

Done

2022-11-29 04:47 UTC, asdfugil requested changes

2022-11-29 04:47 UTC, asdfugil commented on docs/ldid.zh_CN.1
> +.Ar file
`file` is translated 3 lines above, translate it here as well
```suggestion
.Ar 档案
```

2022-11-29 04:47 UTC, asdfugil commented on docs/ldid.zh_TW.1
> +.Ar file
`file` is translated 3 lines above, translate it here as well
```suggestion
.Ar 檔案
```

2022-11-29 04:49 UTC, asdfugil requested changes

2022-11-29 04:49 UTC, asdfugil commented on docs/ldid.zh_TW.1
> +.Dl "ldid -S -Cadhoc,linker-signed 档案"
this is not `zh_CN`

```suggestion
.Dl "ldid -S -Cadhoc,linker-signed 檔案"
```

2022-11-29 13:09 UTC, CRKatri commented on docs/ldid.1
> +with no entitlements, mark it as adhoc and linker-signed signature.
```suggestion
with no entitlements, and mark it as adhoc and linker-signed signature.
```

2022-11-29 13:10 UTC, CRKatri approved these changes
Thank you! All looks good.

2022-11-29 13:11 UTC, merged